### ISSUE TITLE
Support word 'ABS' (abs) from CORE

### ISSUE THREAD

**Issue by davazp** [ams-hackers/gbforth#120]
Implement `ABS`

**Reference:**
https://www.taygeta.com/forth/dpans6.htm#6.1.0690

Before closing this ticket, please ensure:

- [ ] Is the run-time behaviour of the word implemented?
- [ ] Is the compile-time behaviour of the word implemented?
- [ ] Is the interpretation/top-level behaviour of the word implemented?
- [ ] Is the word covered by some tests?

This issue is part of an effort to make gbforth as close to the
standard as possible. It was generated from the following index:

https://www.taygeta.com/forth/dpansf.html

**Comment by tkers** [comment]
Added in 8ac359d3b68da707e13a51a58216085a536aa93c
