### ISSUE TITLE
Merge __start: and main:

### ISSUE THREAD

**Issue by Lapixx** [ams-hackers/gbforth#45]
Currently the kernel emits some initialisation code and a jump to `main` to the rom, and labels this block `__start`.

In practice this means that when you use the `--no-kernel` flag (and write in ASM only), you have to define your entry point with `__start:` instead of `main:`.

It would be nice if this difference was not visible to the user and use `main:` in both cases.

**Comment by davazp** [comment]
This is also invalid now. The prelude will look for a `main` word defined, either as code definition or forth.

It was implemented at 4cc49f9ca4e615f3ff7803a1cf17c148a3255997
