### ISSUE TITLE
Emit (code) words to sym file

### ISSUE THREAD

**Issue by Lapixx** [ams-hackers/gbforth#56]
This was removed during the implementation or the IR/lazy emitting and refactoring of the compiler.

**Comment by davazp** [comment]
This was partially solved by 7ff844439c1b1085a41060d397e6866bcd972892.

However, it seems not all symbols are emitted. For example `main` is missing.. I didn't had the chance to check why.

**Comment by Lapixx** [comment]
Entirely solved by 53e2c86aff7185e3283aaed1fae7e08ce2e84f9e
