### ISSUE TITLE
Support word '#S' (number-sign-s) from CORE

### ISSUE THREAD

**Issue by davazp** [ams-hackers/gbforth#79]
Implement `#S`

**Reference:**
https://www.taygeta.com/forth/dpans6.htm#6.1.0050

Before closing this ticket, please ensure:

- [ ] Is the run-time behaviour of the word implemented?
- [ ] Is the compile-time behaviour of the word implemented?
- [ ] Is the interpretation/top-level behaviour of the word implemented?
- [ ] Is the word covered by some tests?

This issue is part of an effort to make gbforth as close to the
standard as possible. It was generated from the following index:

https://www.taygeta.com/forth/dpansf.html

**Comment by tkers** [comment]
Available from the `formatted-output` lib. Added tests in 4d9fc22144953ed9fe888eb9ebfa8992f2c27c97.
