### ISSUE TITLE
Support word ',' (comma) from CORE

### ISSUE THREAD

**Issue by davazp** [ams-hackers/gbforth#88]
Implement `,`

**Reference:**
https://www.taygeta.com/forth/dpans6.htm#6.1.0150

Before closing this ticket, please ensure:

- [ ] Is the run-time behaviour of the word implemented?
- [ ] Is the compile-time behaviour of the word implemented?
- [ ] Is the interpretation/top-level behaviour of the word implemented?
- [ ] Is the word covered by some tests?

This issue is part of an effort to make gbforth as close to the
standard as possible. It was generated from the following index:

https://www.taygeta.com/forth/dpansf.html

**Comment by davazp** [comment]
@Lapixx Should we document the limitation of `,` being read-only when used in interpretation mode? Or are we going to solve it?

**Comment by Lapixx** [comment]
Good catch. I'll document it for now and open an issue where we can discuss how (or whether we should in the first place) we can handle ROM/RAM context for related words.

**Comment by davazp** [comment]
Ok, then feel free to close this one 👍

**Comment by davazp** [comment]
Actually, include this https://www.taygeta.com/forth/dpanse.htm#E.5 into the new issue!

**Comment by Lapixx** [comment]
Created #283 for ROM/RAM handling.
